// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vending/vending.proto

/*
Package shoppersshop_vendingmachine is a generated protocol buffer package.

It is generated from these files:
	vending/vending.proto

It has these top-level messages:
	GetAllItemCategoriesResponse
	SearchForItemsRequest
	SearchForItemsResponse
	PayViewCartResponse
	PayAddToCartRequest
	PayUpdateOrderRequest
	PayUpdateOrderResponse
	PayReOrderItemsRequest
	PayDeleteOrderRequest
	SessionGetCurrentSessionResponse
	LoginUserRequest
	LoginUserResponse
	SessionCreateSessionResponse
	GetUserByNameRequest
	UpdateUserRequest
	DeleteUserRequest
	GetTransactionVendByIdRequest
	ApiResponse
	Category
	Inventory
	Tag
	User
	Vend
*/
package shoppersshop_vendingmachine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Order Status
type Vend_Vend_Statu int32

const (
	Vend_VEND_STATU_PLACED    Vend_Vend_Statu = 0
	Vend_VEND_STATU_APPROVED  Vend_Vend_Statu = 1
	Vend_VEND_STATU_DELIVERED Vend_Vend_Statu = 2
	Vend_VEND_STATU_CANCELLED Vend_Vend_Statu = 3
)

var Vend_Vend_Statu_name = map[int32]string{
	0: "VEND_STATU_PLACED",
	1: "VEND_STATU_APPROVED",
	2: "VEND_STATU_DELIVERED",
	3: "VEND_STATU_CANCELLED",
}
var Vend_Vend_Statu_value = map[string]int32{
	"VEND_STATU_PLACED":    0,
	"VEND_STATU_APPROVED":  1,
	"VEND_STATU_DELIVERED": 2,
	"VEND_STATU_CANCELLED": 3,
}

func (x Vend_Vend_Statu) String() string {
	return proto.EnumName(Vend_Vend_Statu_name, int32(x))
}
func (Vend_Vend_Statu) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{22, 0} }

type GetAllItemCategoriesResponse struct {
	Items []*GetAllItemCategoriesResponse_Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *GetAllItemCategoriesResponse) Reset()                    { *m = GetAllItemCategoriesResponse{} }
func (m *GetAllItemCategoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllItemCategoriesResponse) ProtoMessage()               {}
func (*GetAllItemCategoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetAllItemCategoriesResponse) GetItems() []*GetAllItemCategoriesResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetAllItemCategoriesResponse_Item struct {
	Categories *Category `protobuf:"bytes,1,opt,name=categories" json:"categories,omitempty"`
	Store      string    `protobuf:"bytes,2,opt,name=store" json:"store,omitempty"`
}

func (m *GetAllItemCategoriesResponse_Item) Reset()         { *m = GetAllItemCategoriesResponse_Item{} }
func (m *GetAllItemCategoriesResponse_Item) String() string { return proto.CompactTextString(m) }
func (*GetAllItemCategoriesResponse_Item) ProtoMessage()    {}
func (*GetAllItemCategoriesResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *GetAllItemCategoriesResponse_Item) GetCategories() *Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *GetAllItemCategoriesResponse_Item) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type SearchForItemsRequest struct {
	// The category names - can pass many items
	Category []string `protobuf:"bytes,1,rep,name=category" json:"category,omitempty"`
	// The item names - can pass many items
	Name []string `protobuf:"bytes,2,rep,name=name" json:"name,omitempty"`
	// The category names - can pass many items
	Price int32 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
}

func (m *SearchForItemsRequest) Reset()                    { *m = SearchForItemsRequest{} }
func (m *SearchForItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchForItemsRequest) ProtoMessage()               {}
func (*SearchForItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchForItemsRequest) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *SearchForItemsRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *SearchForItemsRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type SearchForItemsResponse struct {
	Items []*Inventory `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *SearchForItemsResponse) Reset()                    { *m = SearchForItemsResponse{} }
func (m *SearchForItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchForItemsResponse) ProtoMessage()               {}
func (*SearchForItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchForItemsResponse) GetItems() []*Inventory {
	if m != nil {
		return m.Items
	}
	return nil
}

type PayViewCartResponse struct {
	Items []*Inventory `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *PayViewCartResponse) Reset()                    { *m = PayViewCartResponse{} }
func (m *PayViewCartResponse) String() string            { return proto.CompactTextString(m) }
func (*PayViewCartResponse) ProtoMessage()               {}
func (*PayViewCartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PayViewCartResponse) GetItems() []*Inventory {
	if m != nil {
		return m.Items
	}
	return nil
}

type PayAddToCartRequest struct {
	// A specific item id you wish to purchase
	Id float64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
}

func (m *PayAddToCartRequest) Reset()                    { *m = PayAddToCartRequest{} }
func (m *PayAddToCartRequest) String() string            { return proto.CompactTextString(m) }
func (*PayAddToCartRequest) ProtoMessage()               {}
func (*PayAddToCartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PayAddToCartRequest) GetId() float64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PayUpdateOrderRequest struct {
	// Updated Vend Object
	Body *Vend `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	// ID of order that needs to be updated
	OrderId string `protobuf:"bytes,2,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *PayUpdateOrderRequest) Reset()                    { *m = PayUpdateOrderRequest{} }
func (m *PayUpdateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*PayUpdateOrderRequest) ProtoMessage()               {}
func (*PayUpdateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PayUpdateOrderRequest) GetBody() *Vend {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *PayUpdateOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayUpdateOrderResponse struct {
	CallBack string `protobuf:"bytes,1,opt,name=call_back,json=callBack" json:"call_back,omitempty"`
}

func (m *PayUpdateOrderResponse) Reset()                    { *m = PayUpdateOrderResponse{} }
func (m *PayUpdateOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*PayUpdateOrderResponse) ProtoMessage()               {}
func (*PayUpdateOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PayUpdateOrderResponse) GetCallBack() string {
	if m != nil {
		return m.CallBack
	}
	return ""
}

type PayReOrderItemsRequest struct {
	// ID of order to re-order
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *PayReOrderItemsRequest) Reset()                    { *m = PayReOrderItemsRequest{} }
func (m *PayReOrderItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*PayReOrderItemsRequest) ProtoMessage()               {}
func (*PayReOrderItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PayReOrderItemsRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayDeleteOrderRequest struct {
	// Order ID to delete
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *PayDeleteOrderRequest) Reset()                    { *m = PayDeleteOrderRequest{} }
func (m *PayDeleteOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*PayDeleteOrderRequest) ProtoMessage()               {}
func (*PayDeleteOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PayDeleteOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type SessionGetCurrentSessionResponse struct {
	// The session_id
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *SessionGetCurrentSessionResponse) Reset()         { *m = SessionGetCurrentSessionResponse{} }
func (m *SessionGetCurrentSessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionGetCurrentSessionResponse) ProtoMessage()    {}
func (*SessionGetCurrentSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9}
}

func (m *SessionGetCurrentSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LoginUserRequest struct {
	// The password for login in clear text
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	// The user name for login
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *LoginUserRequest) Reset()                    { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()               {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LoginUserResponse struct {
	// The logged-in user ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LoginUserResponse) Reset()                    { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()               {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LoginUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SessionCreateSessionResponse struct {
	// The user ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *SessionCreateSessionResponse) Reset()                    { *m = SessionCreateSessionResponse{} }
func (m *SessionCreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionCreateSessionResponse) ProtoMessage()               {}
func (*SessionCreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SessionCreateSessionResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserByNameRequest struct {
	// the user or session ID
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *GetUserByNameRequest) Reset()                    { *m = GetUserByNameRequest{} }
func (m *GetUserByNameRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserByNameRequest) ProtoMessage()               {}
func (*GetUserByNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetUserByNameRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	// Updated user object
	Body *User `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	// the user or session ID
	UserId string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateUserRequest) GetBody() *User {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteUserRequest struct {
	// The name that needs to be deleted
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetTransactionVendByIdRequest struct {
	// The id we want to query for transactions
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetTransactionVendByIdRequest) Reset()                    { *m = GetTransactionVendByIdRequest{} }
func (m *GetTransactionVendByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTransactionVendByIdRequest) ProtoMessage()               {}
func (*GetTransactionVendByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetTransactionVendByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ApiResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *ApiResponse) Reset()                    { *m = ApiResponse{} }
func (m *ApiResponse) String() string            { return proto.CompactTextString(m) }
func (*ApiResponse) ProtoMessage()               {}
func (*ApiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ApiResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ApiResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Category struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Inventory struct {
	Cost      int32    `protobuf:"varint,1,opt,name=cost" json:"cost,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name      string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PhotoUrls []string `protobuf:"bytes,4,rep,name=photoUrls" json:"photoUrls,omitempty"`
	Tags      []*Tag   `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Url       string   `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
}

func (m *Inventory) Reset()                    { *m = Inventory{} }
func (m *Inventory) String() string            { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()               {}
func (*Inventory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Inventory) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Inventory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Inventory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Inventory) GetPhotoUrls() []string {
	if m != nil {
		return m.PhotoUrls
	}
	return nil
}

func (m *Inventory) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Inventory) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Tag struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Email     string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=lastName" json:"lastName,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Phone     string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	// User Status
	UserStatus int32  `protobuf:"varint,7,opt,name=userStatus" json:"userStatus,omitempty"`
	Username   string `protobuf:"bytes,8,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetUserStatus() int32 {
	if m != nil {
		return m.UserStatus
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Vend struct {
	Id     string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Items  []*Vend_Item    `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Status Vend_Vend_Statu `protobuf:"varint,3,opt,name=status,enum=shoppersshop_vendingmachine.Vend_Vend_Statu" json:"status,omitempty"`
	Total  int32           `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
}

func (m *Vend) Reset()                    { *m = Vend{} }
func (m *Vend) String() string            { return proto.CompactTextString(m) }
func (*Vend) ProtoMessage()               {}
func (*Vend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Vend) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vend) GetItems() []*Vend_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Vend) GetStatus() Vend_Vend_Statu {
	if m != nil {
		return m.Status
	}
	return Vend_VEND_STATU_PLACED
}

func (m *Vend) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Vend_Item struct {
	Category *Category  `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	Item     *Inventory `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
	// The number of item x bought
	Quantity int32 `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *Vend_Item) Reset()                    { *m = Vend_Item{} }
func (m *Vend_Item) String() string            { return proto.CompactTextString(m) }
func (*Vend_Item) ProtoMessage()               {}
func (*Vend_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22, 0} }

func (m *Vend_Item) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Vend_Item) GetItem() *Inventory {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Vend_Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAllItemCategoriesResponse)(nil), "shoppersshop_vendingmachine.GetAllItemCategoriesResponse")
	proto.RegisterType((*GetAllItemCategoriesResponse_Item)(nil), "shoppersshop_vendingmachine.GetAllItemCategoriesResponse.Item")
	proto.RegisterType((*SearchForItemsRequest)(nil), "shoppersshop_vendingmachine.SearchForItemsRequest")
	proto.RegisterType((*SearchForItemsResponse)(nil), "shoppersshop_vendingmachine.SearchForItemsResponse")
	proto.RegisterType((*PayViewCartResponse)(nil), "shoppersshop_vendingmachine.PayViewCartResponse")
	proto.RegisterType((*PayAddToCartRequest)(nil), "shoppersshop_vendingmachine.PayAddToCartRequest")
	proto.RegisterType((*PayUpdateOrderRequest)(nil), "shoppersshop_vendingmachine.PayUpdateOrderRequest")
	proto.RegisterType((*PayUpdateOrderResponse)(nil), "shoppersshop_vendingmachine.PayUpdateOrderResponse")
	proto.RegisterType((*PayReOrderItemsRequest)(nil), "shoppersshop_vendingmachine.PayReOrderItemsRequest")
	proto.RegisterType((*PayDeleteOrderRequest)(nil), "shoppersshop_vendingmachine.PayDeleteOrderRequest")
	proto.RegisterType((*SessionGetCurrentSessionResponse)(nil), "shoppersshop_vendingmachine.SessionGetCurrentSessionResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "shoppersshop_vendingmachine.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "shoppersshop_vendingmachine.LoginUserResponse")
	proto.RegisterType((*SessionCreateSessionResponse)(nil), "shoppersshop_vendingmachine.SessionCreateSessionResponse")
	proto.RegisterType((*GetUserByNameRequest)(nil), "shoppersshop_vendingmachine.GetUserByNameRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "shoppersshop_vendingmachine.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "shoppersshop_vendingmachine.DeleteUserRequest")
	proto.RegisterType((*GetTransactionVendByIdRequest)(nil), "shoppersshop_vendingmachine.GetTransactionVendByIdRequest")
	proto.RegisterType((*ApiResponse)(nil), "shoppersshop_vendingmachine.ApiResponse")
	proto.RegisterType((*Category)(nil), "shoppersshop_vendingmachine.Category")
	proto.RegisterType((*Inventory)(nil), "shoppersshop_vendingmachine.Inventory")
	proto.RegisterType((*Tag)(nil), "shoppersshop_vendingmachine.Tag")
	proto.RegisterType((*User)(nil), "shoppersshop_vendingmachine.User")
	proto.RegisterType((*Vend)(nil), "shoppersshop_vendingmachine.Vend")
	proto.RegisterType((*Vend_Item)(nil), "shoppersshop_vendingmachine.Vend.Item")
	proto.RegisterEnum("shoppersshop_vendingmachine.Vend_Vend_Statu", Vend_Vend_Statu_name, Vend_Vend_Statu_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SHOPPERSSHOP_VendingMachineService service

type SHOPPERSSHOP_VendingMachineServiceClient interface {
	// Finds Pets by status
	//
	// Get all stores once can vend the inventory by name
	GetAllItemCategories(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*GetAllItemCategoriesResponse, error)
	// Finds inventory items by query params
	//
	// Search the inventory by query params
	SearchForItems(ctx context.Context, in *SearchForItemsRequest, opts ...grpc.CallOption) (*SearchForItemsResponse, error)
	// See all items in your virtual cart
	//
	// Shows all items in your cart
	PayViewCart(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PayViewCartResponse, error)
	// Initilize a vending transaction
	//
	// Purchases all items in your cart
	PayPurchaseCart(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Add an item via id to your cart
	PayAddToCart(ctx context.Context, in *PayAddToCartRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Updates an old order
	//
	// Updates an old order IF it is not completed
	PayUpdateOrder(ctx context.Context, in *PayUpdateOrderRequest, opts ...grpc.CallOption) (*PayUpdateOrderResponse, error)
	// Re-order items
	//
	// Adds all items from the given order back to the cart
	PayReOrderItems(ctx context.Context, in *PayReOrderItemsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Deletes a order IF it is not complete
	//
	// Delete an outstanding order
	PayDeleteOrder(ctx context.Context, in *PayDeleteOrderRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Get the session
	//
	// Returns the current session ID or creates one
	SessionGetCurrentSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionGetCurrentSessionResponse, error)
	// Logs user into the system
	//
	// Logs in the current user into the vending machine
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	// Logs out current logged in user session
	//
	// Logs out the given user
	LogoutUser(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Creates a user session
	//
	// Creates a session with the given user
	SessionCreateSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionCreateSessionResponse, error)
	// Get session or user by ID
	//
	// Gets the session/user represented by the passed UUID
	GetUserByName(ctx context.Context, in *GetUserByNameRequest, opts ...grpc.CallOption) (*User, error)
	// Updated user
	//
	// This can only be done by the logged in user.
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Delete user
	//
	// Deletes current user.
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// web-hook endpoint representing vended items by this session
	//
	// The endpoint representing all of the items you've ever purchased - thanks!
	GetUserVen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Vend, error)
	// Web-hook and transaction query
	//
	// This endpoint gives access to transactions created by {TransactionId, UserId}
	GetTransactionVendById(ctx context.Context, in *GetTransactionVendByIdRequest, opts ...grpc.CallOption) (*Vend, error)
}

type sHOPPERSSHOP_VendingMachineServiceClient struct {
	cc *grpc.ClientConn
}

func NewSHOPPERSSHOP_VendingMachineServiceClient(cc *grpc.ClientConn) SHOPPERSSHOP_VendingMachineServiceClient {
	return &sHOPPERSSHOP_VendingMachineServiceClient{cc}
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) GetAllItemCategories(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*GetAllItemCategoriesResponse, error) {
	out := new(GetAllItemCategoriesResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetAllItemCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SearchForItems(ctx context.Context, in *SearchForItemsRequest, opts ...grpc.CallOption) (*SearchForItemsResponse, error) {
	out := new(SearchForItemsResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SearchForItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayViewCart(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PayViewCartResponse, error) {
	out := new(PayViewCartResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayViewCart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayPurchaseCart(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayPurchaseCart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayAddToCart(ctx context.Context, in *PayAddToCartRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayAddToCart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayUpdateOrder(ctx context.Context, in *PayUpdateOrderRequest, opts ...grpc.CallOption) (*PayUpdateOrderResponse, error) {
	out := new(PayUpdateOrderResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayUpdateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayReOrderItems(ctx context.Context, in *PayReOrderItemsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayReOrderItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayDeleteOrder(ctx context.Context, in *PayDeleteOrderRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayDeleteOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionGetCurrentSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionGetCurrentSessionResponse, error) {
	out := new(SessionGetCurrentSessionResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionGetCurrentSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/LoginUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) LogoutUser(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/LogoutUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionCreateSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionCreateSessionResponse, error) {
	out := new(SessionCreateSessionResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionCreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) GetUserByName(ctx context.Context, in *GetUserByNameRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetUserByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) GetUserVen(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Vend, error) {
	out := new(Vend)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetUserVen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) GetTransactionVendById(ctx context.Context, in *GetTransactionVendByIdRequest, opts ...grpc.CallOption) (*Vend, error) {
	out := new(Vend)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetTransactionVendById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SHOPPERSSHOP_VendingMachineService service

type SHOPPERSSHOP_VendingMachineServiceServer interface {
	// Finds Pets by status
	//
	// Get all stores once can vend the inventory by name
	GetAllItemCategories(context.Context, *google_protobuf.Empty) (*GetAllItemCategoriesResponse, error)
	// Finds inventory items by query params
	//
	// Search the inventory by query params
	SearchForItems(context.Context, *SearchForItemsRequest) (*SearchForItemsResponse, error)
	// See all items in your virtual cart
	//
	// Shows all items in your cart
	PayViewCart(context.Context, *google_protobuf.Empty) (*PayViewCartResponse, error)
	// Initilize a vending transaction
	//
	// Purchases all items in your cart
	PayPurchaseCart(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	// Add an item via id to your cart
	PayAddToCart(context.Context, *PayAddToCartRequest) (*google_protobuf.Empty, error)
	// Updates an old order
	//
	// Updates an old order IF it is not completed
	PayUpdateOrder(context.Context, *PayUpdateOrderRequest) (*PayUpdateOrderResponse, error)
	// Re-order items
	//
	// Adds all items from the given order back to the cart
	PayReOrderItems(context.Context, *PayReOrderItemsRequest) (*google_protobuf.Empty, error)
	// Deletes a order IF it is not complete
	//
	// Delete an outstanding order
	PayDeleteOrder(context.Context, *PayDeleteOrderRequest) (*google_protobuf.Empty, error)
	// Get the session
	//
	// Returns the current session ID or creates one
	SessionGetCurrentSession(context.Context, *google_protobuf.Empty) (*SessionGetCurrentSessionResponse, error)
	// Logs user into the system
	//
	// Logs in the current user into the vending machine
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	// Logs out current logged in user session
	//
	// Logs out the given user
	LogoutUser(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	// Creates a user session
	//
	// Creates a session with the given user
	SessionCreateSession(context.Context, *google_protobuf.Empty) (*SessionCreateSessionResponse, error)
	// Get session or user by ID
	//
	// Gets the session/user represented by the passed UUID
	GetUserByName(context.Context, *GetUserByNameRequest) (*User, error)
	// Updated user
	//
	// This can only be done by the logged in user.
	UpdateUser(context.Context, *UpdateUserRequest) (*google_protobuf.Empty, error)
	// Delete user
	//
	// Deletes current user.
	DeleteUser(context.Context, *DeleteUserRequest) (*google_protobuf.Empty, error)
	// web-hook endpoint representing vended items by this session
	//
	// The endpoint representing all of the items you've ever purchased - thanks!
	GetUserVen(context.Context, *google_protobuf.Empty) (*Vend, error)
	// Web-hook and transaction query
	//
	// This endpoint gives access to transactions created by {TransactionId, UserId}
	GetTransactionVendById(context.Context, *GetTransactionVendByIdRequest) (*Vend, error)
}

func RegisterSHOPPERSSHOP_VendingMachineServiceServer(s *grpc.Server, srv SHOPPERSSHOP_VendingMachineServiceServer) {
	s.RegisterService(&_SHOPPERSSHOP_VendingMachineService_serviceDesc, srv)
}

func _SHOPPERSSHOP_VendingMachineService_GetAllItemCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetAllItemCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetAllItemCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetAllItemCategories(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SearchForItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchForItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SearchForItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SearchForItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SearchForItems(ctx, req.(*SearchForItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayViewCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayViewCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayViewCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayViewCart(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayPurchaseCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayPurchaseCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayPurchaseCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayPurchaseCart(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayAddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayAddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayAddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayAddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayAddToCart(ctx, req.(*PayAddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayUpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayUpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayUpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayUpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayUpdateOrder(ctx, req.(*PayUpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayReOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReOrderItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayReOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayReOrderItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayReOrderItems(ctx, req.(*PayReOrderItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayDeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayDeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayDeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayDeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayDeleteOrder(ctx, req.(*PayDeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionGetCurrentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionGetCurrentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionGetCurrentSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionGetCurrentSession(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/LogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).LogoutUser(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionCreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionCreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionCreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionCreateSession(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_GetUserByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetUserByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetUserByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetUserByName(ctx, req.(*GetUserByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_GetUserVen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetUserVen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetUserVen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetUserVen(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_GetTransactionVendById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionVendByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetTransactionVendById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/GetTransactionVendById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).GetTransactionVendById(ctx, req.(*GetTransactionVendByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SHOPPERSSHOP_VendingMachineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService",
	HandlerType: (*SHOPPERSSHOP_VendingMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllItemCategories",
			Handler:    _SHOPPERSSHOP_VendingMachineService_GetAllItemCategories_Handler,
		},
		{
			MethodName: "SearchForItems",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SearchForItems_Handler,
		},
		{
			MethodName: "PayViewCart",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayViewCart_Handler,
		},
		{
			MethodName: "PayPurchaseCart",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayPurchaseCart_Handler,
		},
		{
			MethodName: "PayAddToCart",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayAddToCart_Handler,
		},
		{
			MethodName: "PayUpdateOrder",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayUpdateOrder_Handler,
		},
		{
			MethodName: "PayReOrderItems",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayReOrderItems_Handler,
		},
		{
			MethodName: "PayDeleteOrder",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayDeleteOrder_Handler,
		},
		{
			MethodName: "SessionGetCurrentSession",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionGetCurrentSession_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_LogoutUser_Handler,
		},
		{
			MethodName: "SessionCreateSession",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionCreateSession_Handler,
		},
		{
			MethodName: "GetUserByName",
			Handler:    _SHOPPERSSHOP_VendingMachineService_GetUserByName_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUserVen",
			Handler:    _SHOPPERSSHOP_VendingMachineService_GetUserVen_Handler,
		},
		{
			MethodName: "GetTransactionVendById",
			Handler:    _SHOPPERSSHOP_VendingMachineService_GetTransactionVendById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vending/vending.proto",
}

func init() { proto.RegisterFile("vending/vending.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0x7e, 0xd7, 0x1f, 0x69, 0x7c, 0xf2, 0x12, 0x9c, 0x69, 0x92, 0xba, 0x9b, 0xa4, 0xb8, 0xab,
	0x16, 0x42, 0x29, 0x36, 0x4d, 0xa9, 0x10, 0x15, 0x20, 0xb9, 0xb6, 0x09, 0x46, 0x21, 0xb1, 0xd6,
	0x8e, 0xef, 0x90, 0x99, 0x78, 0xa7, 0xf6, 0xaa, 0xeb, 0xdd, 0xed, 0xce, 0xb8, 0x95, 0xa9, 0xaa,
	0x02, 0x57, 0x48, 0x08, 0x6e, 0x90, 0xb8, 0x45, 0x70, 0xc7, 0x1f, 0xe1, 0x0f, 0xc0, 0x0d, 0xf7,
	0xfc, 0x06, 0xae, 0xd1, 0xcc, 0xce, 0xda, 0xeb, 0x8f, 0xdd, 0x4d, 0x2a, 0x6e, 0x92, 0x3d, 0x33,
	0x73, 0xce, 0xf3, 0x9c, 0x33, 0x33, 0x67, 0x1e, 0xc3, 0xd6, 0x13, 0x62, 0x1b, 0xa6, 0xdd, 0x2f,
	0xcb, 0xff, 0x25, 0xd7, 0x73, 0x98, 0x83, 0x76, 0xe8, 0xc0, 0x71, 0x5d, 0xe2, 0x51, 0xfe, 0xbf,
	0x2b, 0xe7, 0x86, 0xb8, 0x37, 0x30, 0x6d, 0xa2, 0xee, 0xf4, 0x1d, 0xa7, 0x6f, 0x91, 0xb2, 0x58,
	0x7a, 0x36, 0x7a, 0x58, 0x26, 0x43, 0x97, 0x8d, 0x7d, 0x4f, 0x75, 0x57, 0x4e, 0x62, 0xd7, 0x2c,
	0x63, 0xdb, 0x76, 0x18, 0x66, 0xa6, 0x63, 0x53, 0x7f, 0x56, 0xfb, 0x4b, 0x81, 0xdd, 0x43, 0xc2,
	0x2a, 0x96, 0xd5, 0x60, 0x64, 0x58, 0xc5, 0x8c, 0xf4, 0x1d, 0xcf, 0x24, 0x54, 0x27, 0xd4, 0x75,
	0x6c, 0x4a, 0x50, 0x1b, 0xb2, 0x26, 0x23, 0x43, 0x5a, 0x50, 0x8a, 0xe9, 0xfd, 0xb5, 0x83, 0x8f,
	0x4a, 0x31, 0x44, 0x4a, 0x71, 0x91, 0x4a, 0x7c, 0x58, 0xf7, 0x83, 0xa9, 0x3d, 0xc8, 0x70, 0x13,
	0xd5, 0x01, 0x7a, 0x93, 0x95, 0x05, 0xa5, 0xa8, 0xec, 0xaf, 0x1d, 0xdc, 0x8c, 0x85, 0x90, 0x81,
	0xc7, 0x7a, 0xc8, 0x11, 0x6d, 0x42, 0x96, 0x32, 0xc7, 0x23, 0x85, 0x54, 0x51, 0xd9, 0xcf, 0xe9,
	0xbe, 0xa1, 0x7d, 0x0e, 0x5b, 0x2d, 0x82, 0xbd, 0xde, 0xe0, 0x63, 0xc7, 0xe3, 0x68, 0x54, 0x27,
	0x8f, 0x47, 0x84, 0x32, 0xa4, 0xc2, 0xaa, 0x74, 0x1e, 0x8b, 0xb4, 0x72, 0xfa, 0xc4, 0x46, 0x08,
	0x32, 0x36, 0x1e, 0xf2, 0x48, 0x7c, 0x5c, 0x7c, 0xf3, 0xf0, 0xae, 0x67, 0xf6, 0x48, 0x21, 0x5d,
	0x54, 0xf6, 0xb3, 0xba, 0x6f, 0x68, 0x1d, 0xd8, 0x9e, 0x0f, 0x2f, 0x6b, 0xf6, 0xc1, 0x6c, 0xcd,
	0x5e, 0x8f, 0x4d, 0xa8, 0x61, 0x3f, 0x21, 0x36, 0xe3, 0x19, 0xf9, 0x4e, 0x5a, 0x0b, 0x2e, 0x37,
	0xf1, 0xb8, 0x63, 0x92, 0xa7, 0x55, 0xec, 0xb1, 0xff, 0x28, 0xe8, 0x4d, 0x11, 0xb4, 0x62, 0x18,
	0x6d, 0xc7, 0x8f, 0xea, 0x57, 0x62, 0x1d, 0x52, 0xa6, 0x21, 0xea, 0xae, 0xe8, 0x29, 0xd3, 0xd0,
	0x06, 0xb0, 0xd5, 0xc4, 0xe3, 0x53, 0xd7, 0xc0, 0x8c, 0x9c, 0x78, 0x06, 0xf1, 0x82, 0x85, 0xf7,
	0x20, 0x73, 0xe6, 0x18, 0x63, 0xb9, 0x45, 0xd7, 0x63, 0xc1, 0x3b, 0xc4, 0x36, 0x74, 0xb1, 0x1c,
	0x15, 0xe0, 0x92, 0xc3, 0xc3, 0x34, 0x0c, 0xb9, 0x35, 0x81, 0xa9, 0xdd, 0x83, 0xed, 0x79, 0x24,
	0x99, 0xe8, 0x0e, 0xe4, 0x7a, 0xd8, 0xb2, 0xba, 0x67, 0xb8, 0xf7, 0x48, 0xe0, 0x89, 0xed, 0xb1,
	0xac, 0x07, 0xb8, 0xf7, 0x48, 0x3b, 0x10, 0x6e, 0xba, 0xef, 0x32, 0xb3, 0xa9, 0x21, 0x28, 0x65,
	0x16, 0xea, 0x8e, 0x48, 0xaa, 0x46, 0x2c, 0x32, 0x97, 0x54, 0xb4, 0x4b, 0x05, 0x8a, 0x2d, 0x42,
	0xa9, 0xe9, 0xd8, 0x87, 0x84, 0x55, 0x47, 0x9e, 0x47, 0x6c, 0x26, 0x07, 0x26, 0x3c, 0xf7, 0x00,
	0xa8, 0x3f, 0xd4, 0x35, 0x83, 0x00, 0x39, 0x39, 0xd2, 0x30, 0xb4, 0x4f, 0x21, 0x7f, 0xe4, 0xf4,
	0x4d, 0xfb, 0x94, 0x4e, 0x01, 0x55, 0x58, 0x75, 0x31, 0xa5, 0x4f, 0x1d, 0x2f, 0x70, 0x98, 0xd8,
	0x7c, 0x6e, 0x44, 0x89, 0x27, 0x0f, 0x9f, 0x98, 0x0b, 0x6c, 0xed, 0x36, 0x6c, 0x84, 0x62, 0x49,
	0xfc, 0x2b, 0x70, 0x89, 0x2f, 0x98, 0x82, 0xaf, 0x70, 0xb3, 0x61, 0x68, 0xef, 0xc1, 0xae, 0xe4,
	0x5a, 0xf5, 0x08, 0x66, 0x64, 0x9e, 0x78, 0xa4, 0x63, 0x09, 0x36, 0x0f, 0x09, 0xe3, 0x20, 0x0f,
	0xc6, 0xc7, 0x78, 0x48, 0x02, 0xda, 0xdb, 0x20, 0x57, 0xcc, 0xad, 0x3f, 0x83, 0x0d, 0x7f, 0x03,
	0xc3, 0x39, 0x5e, 0xe4, 0xa4, 0x08, 0x3f, 0xff, 0xa4, 0x4c, 0x31, 0x52, 0x33, 0x18, 0x6f, 0xc1,
	0x86, 0xbf, 0x73, 0x61, 0x8c, 0x28, 0x42, 0x65, 0xd8, 0x3b, 0x24, 0xac, 0xed, 0x61, 0x9b, 0xe2,
	0x1e, 0x6f, 0x73, 0xfc, 0x28, 0x3e, 0x18, 0x37, 0x8c, 0xc5, 0xf3, 0x9e, 0x13, 0xe7, 0xfd, 0x04,
	0xd6, 0x2a, 0xae, 0x39, 0xa9, 0x0c, 0x82, 0x4c, 0xcf, 0x31, 0x88, 0x58, 0x90, 0xd5, 0xc5, 0x37,
	0x3f, 0x24, 0x43, 0x42, 0x29, 0xee, 0x07, 0xdb, 0x12, 0x98, 0x7c, 0x35, 0x1b, 0xbb, 0x7e, 0x57,
	0xc8, 0xe9, 0xe2, 0x5b, 0x2b, 0xc1, 0x6a, 0xd0, 0xa1, 0xe6, 0xc1, 0x42, 0xad, 0x45, 0x09, 0x5a,
	0x8b, 0xf6, 0x9b, 0x02, 0xb9, 0xc9, 0x65, 0xf5, 0xf1, 0x29, 0x9b, 0xe2, 0x4f, 0x28, 0xa7, 0x16,
	0xa2, 0xa4, 0xa7, 0x51, 0xd0, 0x2e, 0xe4, 0xdc, 0x81, 0xc3, 0x9c, 0x53, 0xcf, 0xa2, 0x85, 0x8c,
	0xe8, 0x5c, 0xd3, 0x01, 0xf4, 0x2e, 0x64, 0x18, 0xee, 0xd3, 0x42, 0x56, 0x34, 0x8e, 0x62, 0xec,
	0x8e, 0xb4, 0x71, 0x5f, 0x17, 0xab, 0x51, 0x1e, 0xd2, 0x23, 0xcf, 0x2a, 0xac, 0x08, 0x18, 0xfe,
	0xa9, 0xbd, 0x09, 0xe9, 0x36, 0xee, 0x9f, 0x2b, 0xad, 0x3f, 0x15, 0xc8, 0xf0, 0x0d, 0xe3, 0xad,
	0x93, 0x0c, 0xb1, 0x69, 0xc9, 0xf5, 0xbe, 0xc1, 0xf9, 0x3e, 0x34, 0x3d, 0xca, 0x8e, 0xa7, 0x7e,
	0xd3, 0x01, 0x09, 0x90, 0x9e, 0x00, 0xa8, 0xb0, 0x6a, 0x61, 0xb9, 0x38, 0xe3, 0xdf, 0x8c, 0xc0,
	0x9e, 0xb9, 0x51, 0xd9, 0xb9, 0x1b, 0xc5, 0xdb, 0xf6, 0xc0, 0xb1, 0x89, 0xcc, 0xc1, 0x37, 0xd0,
	0x35, 0x00, 0x7e, 0x5a, 0x5a, 0x0c, 0xb3, 0x11, 0x2d, 0x5c, 0x12, 0x95, 0x0e, 0x8d, 0xcc, 0xdc,
	0xc3, 0xd5, 0xb9, 0x7b, 0xf8, 0x7b, 0x1a, 0x32, 0xfc, 0x48, 0x2d, 0xd4, 0x60, 0xd2, 0x9c, 0x53,
	0xe7, 0x68, 0xce, 0x3c, 0x42, 0xf8, 0x35, 0x44, 0x35, 0x58, 0xa1, 0x3e, 0x1d, 0x9e, 0xf4, 0xfa,
	0xc1, 0xed, 0x64, 0x77, 0xfe, 0xa7, 0x2b, 0x18, 0xeb, 0xd2, 0x97, 0xa7, 0xcb, 0x1c, 0x86, 0x2d,
	0x51, 0xa3, 0xac, 0xee, 0x1b, 0xea, 0x2f, 0x8a, 0x7c, 0x6a, 0x2b, 0x33, 0x8f, 0xde, 0x05, 0x1e,
	0xda, 0xe9, 0xdb, 0x78, 0x1f, 0x32, 0x9c, 0xb0, 0xd8, 0xb1, 0xf3, 0xbf, 0x40, 0xc2, 0x87, 0x97,
	0xf5, 0xf1, 0x08, 0xdb, 0xcc, 0x64, 0x63, 0xf9, 0x8c, 0x4e, 0x6c, 0xcd, 0x05, 0x98, 0xe6, 0x83,
	0xb6, 0x60, 0xa3, 0x53, 0x3f, 0xae, 0x75, 0x5b, 0xed, 0x4a, 0xfb, 0xb4, 0xdb, 0x3c, 0xaa, 0x54,
	0xeb, 0xb5, 0xfc, 0xff, 0xd0, 0x15, 0xb8, 0x1c, 0x1a, 0xae, 0x34, 0x9b, 0xfa, 0x49, 0xa7, 0x5e,
	0xcb, 0x2b, 0xa8, 0x00, 0x9b, 0xa1, 0x89, 0x5a, 0xfd, 0xa8, 0xd1, 0xa9, 0xeb, 0xf5, 0x5a, 0x3e,
	0x35, 0x37, 0x53, 0xad, 0x1c, 0x57, 0xeb, 0x47, 0x47, 0xf5, 0x5a, 0x3e, 0x7d, 0xf0, 0xcf, 0x06,
	0x68, 0xad, 0x4f, 0x4e, 0x9a, 0xcd, 0xba, 0xde, 0xe2, 0xff, 0xbb, 0x1d, 0x9f, 0xfd, 0x67, 0x3e,
	0xfb, 0x16, 0xf1, 0x9e, 0x98, 0x3d, 0x82, 0xbe, 0x55, 0x44, 0x47, 0x5c, 0xd0, 0x34, 0x68, 0xbb,
	0xe4, 0xab, 0xaa, 0x52, 0x20, 0xb9, 0x4a, 0x75, 0x2e, 0xb9, 0xd4, 0xf7, 0x5f, 0x5a, 0x1e, 0x69,
	0x7b, 0xdf, 0xfc, 0xf1, 0xf7, 0x8f, 0xa9, 0x2b, 0x68, 0xab, 0x3c, 0x51, 0x80, 0x77, 0xca, 0xe6,
	0xa4, 0x35, 0xfc, 0xac, 0xc0, 0xfa, 0xac, 0xdc, 0x40, 0x07, 0xb1, 0x60, 0x4b, 0xa5, 0x8f, 0x7a,
	0xf7, 0x42, 0x3e, 0x92, 0xda, 0x0d, 0x41, 0xed, 0x1a, 0xda, 0x5d, 0x4a, 0xad, 0x4c, 0x85, 0x17,
	0x1a, 0xc3, 0x5a, 0x48, 0xb7, 0x44, 0x96, 0xe8, 0x9d, 0x58, 0x06, 0x4b, 0x94, 0x8f, 0x56, 0x14,
	0xf0, 0x2a, 0x2a, 0x84, 0xe1, 0x5d, 0x3c, 0x2e, 0xbb, 0x23, 0xaf, 0x37, 0xc0, 0x94, 0xa0, 0x1e,
	0xbc, 0xda, 0xc4, 0xe3, 0xa6, 0x34, 0x63, 0xe1, 0x23, 0xc6, 0x03, 0x10, 0x2d, 0x1a, 0xe4, 0x05,
	0xfc, 0x3f, 0x2c, 0xa1, 0x50, 0x62, 0x22, 0xf3, 0x6a, 0x2b, 0x12, 0xfb, 0xa6, 0xc0, 0x7e, 0x4d,
	0xdd, 0x8b, 0xc2, 0x2e, 0x3f, 0x33, 0x8d, 0xe7, 0xe8, 0x57, 0x05, 0xd6, 0x67, 0x35, 0x53, 0xc2,
	0x11, 0x58, 0x2a, 0xe5, 0x12, 0x8e, 0xc0, 0x72, 0x51, 0xa6, 0xbd, 0x21, 0x28, 0x5e, 0x57, 0xaf,
	0xce, 0x53, 0x7c, 0x26, 0x25, 0xd3, 0xf3, 0xfb, 0xfe, 0x3b, 0xfe, 0xb5, 0x22, 0xf6, 0x22, 0xac,
	0xd0, 0x50, 0x22, 0xe2, 0x12, 0x3d, 0x17, 0x59, 0xac, 0xeb, 0x82, 0xc9, 0x8e, 0x16, 0xcd, 0x04,
	0xbd, 0x10, 0x75, 0x0a, 0x09, 0xbe, 0xe4, 0x3a, 0x2d, 0xaa, 0xc3, 0x24, 0x02, 0xb7, 0x62, 0x08,
	0xfc, 0xa0, 0x40, 0x21, 0x4a, 0x3f, 0x46, 0x9e, 0xcc, 0x0f, 0x13, 0xae, 0x66, 0xbc, 0x1c, 0xd5,
	0x76, 0x04, 0xad, 0x2d, 0x74, 0x39, 0x4c, 0x4b, 0xca, 0x51, 0xf4, 0xbd, 0x02, 0xb9, 0x89, 0x82,
	0x44, 0x6f, 0xc7, 0x22, 0xcd, 0xab, 0x56, 0xb5, 0x74, 0xde, 0xe5, 0x92, 0x89, 0x2c, 0x10, 0xba,
	0xba, 0x84, 0x49, 0xd9, 0xe2, 0xcb, 0xd1, 0x17, 0x00, 0x47, 0x4e, 0xdf, 0x19, 0x09, 0xb1, 0x79,
	0xe1, 0xbb, 0xaa, 0x09, 0x80, 0x5d, 0x4d, 0x8d, 0x00, 0x70, 0x46, 0x0c, 0x7d, 0xa7, 0xc0, 0xe6,
	0x32, 0x15, 0xfc, 0x92, 0xad, 0x3b, 0x4e, 0x50, 0x2f, 0xef, 0x1d, 0x01, 0x1f, 0x2e, 0x1e, 0x38,
	0x9b, 0x57, 0x66, 0xa4, 0x35, 0xba, 0x93, 0xf4, 0x52, 0x2c, 0xc8, 0x70, 0x35, 0x59, 0x4b, 0x2f,
	0xef, 0xd4, 0x01, 0x93, 0x67, 0xbe, 0x4a, 0x7e, 0x8e, 0xbe, 0x52, 0x00, 0xa6, 0xc2, 0x1d, 0xc5,
	0xef, 0xef, 0x82, 0xc2, 0x8f, 0xdc, 0x96, 0x5b, 0x02, 0xfc, 0x86, 0x1a, 0x0b, 0x2e, 0xdb, 0xc4,
	0x97, 0x00, 0x53, 0x59, 0x9f, 0xc0, 0x60, 0x41, 0xff, 0x47, 0x32, 0x90, 0xe9, 0xdf, 0x8a, 0x4f,
	0x1f, 0x03, 0xc8, 0xfa, 0x76, 0x48, 0xf4, 0x79, 0x48, 0xfe, 0x8d, 0xab, 0x15, 0x04, 0x1c, 0x42,
	0xf9, 0x30, 0x1c, 0xff, 0x44, 0x3f, 0x29, 0xb0, 0xbd, 0xfc, 0x97, 0x08, 0xba, 0x9f, 0xb4, 0xf1,
	0xd1, 0x3f, 0x5f, 0xce, 0xc3, 0x69, 0xa9, 0x8c, 0xe0, 0x9f, 0xe2, 0x0d, 0x39, 0x5b, 0x11, 0x59,
	0xde, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x8c, 0x83, 0x52, 0x67, 0x12, 0x00, 0x00,
}
