// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vending/vending.proto

/*
Package shoppersshop_vendingmachine is a generated protocol buffer package.

It is generated from these files:
	vending/vending.proto

It has these top-level messages:
	InventorySearchAllItemCategoriesResponse
	InventorySearchForItemsRequest
	InventorySearchForItemsResponse
	PayViewPaymentInfoResponse
	PayViewCartResponse
	PayPurchaseCartRequest
	PayPurchaseCartResponse
	PayAddToCartRequest
	PayUpdateOrderRequest
	PayUpdateOrderResponse
	PayReOrderItemsRequest
	PayDeleteOrderRequest
	SessionGetCurrentSessionResponse
	SessionLoginUserRequest
	SessionCreateSessionResponse
	SessionCreateUserRequest
	SessionCreateUserResponse
	SessionGetUserByUserIdRequest
	SessionUpdateUserRequest
	SessionDeleteUserRequest
	VendGetVendByIdRequest
	ApiResponse
	Category
	Currency
	Empty
	Inventory
	Tag
	User
	Vend
*/
package shoppersshop_vendingmachine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Order Status
type Vend_Vend_Statu int32

const (
	Vend_VEND_STATU_PLACED    Vend_Vend_Statu = 0
	Vend_VEND_STATU_APPROVED  Vend_Vend_Statu = 1
	Vend_VEND_STATU_DELIVERED Vend_Vend_Statu = 2
	Vend_VEND_STATU_CANCELLED Vend_Vend_Statu = 3
)

var Vend_Vend_Statu_name = map[int32]string{
	0: "VEND_STATU_PLACED",
	1: "VEND_STATU_APPROVED",
	2: "VEND_STATU_DELIVERED",
	3: "VEND_STATU_CANCELLED",
}
var Vend_Vend_Statu_value = map[string]int32{
	"VEND_STATU_PLACED":    0,
	"VEND_STATU_APPROVED":  1,
	"VEND_STATU_DELIVERED": 2,
	"VEND_STATU_CANCELLED": 3,
}

func (x Vend_Vend_Statu) String() string {
	return proto.EnumName(Vend_Vend_Statu_name, int32(x))
}
func (Vend_Vend_Statu) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{28, 0} }

type InventorySearchAllItemCategoriesResponse struct {
	Items []*InventorySearchAllItemCategoriesResponse_Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *InventorySearchAllItemCategoriesResponse) Reset() {
	*m = InventorySearchAllItemCategoriesResponse{}
}
func (m *InventorySearchAllItemCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*InventorySearchAllItemCategoriesResponse) ProtoMessage()    {}
func (*InventorySearchAllItemCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *InventorySearchAllItemCategoriesResponse) GetItems() []*InventorySearchAllItemCategoriesResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type InventorySearchAllItemCategoriesResponse_Item struct {
	Categories *Category `protobuf:"bytes,1,opt,name=categories" json:"categories,omitempty"`
	Store      string    `protobuf:"bytes,2,opt,name=store" json:"store,omitempty"`
}

func (m *InventorySearchAllItemCategoriesResponse_Item) Reset() {
	*m = InventorySearchAllItemCategoriesResponse_Item{}
}
func (m *InventorySearchAllItemCategoriesResponse_Item) String() string {
	return proto.CompactTextString(m)
}
func (*InventorySearchAllItemCategoriesResponse_Item) ProtoMessage() {}
func (*InventorySearchAllItemCategoriesResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *InventorySearchAllItemCategoriesResponse_Item) GetCategories() *Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *InventorySearchAllItemCategoriesResponse_Item) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type InventorySearchForItemsRequest struct {
	// The category names - can pass many items
	Category []string `protobuf:"bytes,1,rep,name=category" json:"category,omitempty"`
	// The item names - can pass many items
	Name []string `protobuf:"bytes,2,rep,name=name" json:"name,omitempty"`
	// The category names - can pass many items
	Price int32 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
}

func (m *InventorySearchForItemsRequest) Reset()                    { *m = InventorySearchForItemsRequest{} }
func (m *InventorySearchForItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*InventorySearchForItemsRequest) ProtoMessage()               {}
func (*InventorySearchForItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InventorySearchForItemsRequest) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *InventorySearchForItemsRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *InventorySearchForItemsRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type InventorySearchForItemsResponse struct {
	Items []*Inventory `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *InventorySearchForItemsResponse) Reset()                    { *m = InventorySearchForItemsResponse{} }
func (m *InventorySearchForItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*InventorySearchForItemsResponse) ProtoMessage()               {}
func (*InventorySearchForItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InventorySearchForItemsResponse) GetItems() []*Inventory {
	if m != nil {
		return m.Items
	}
	return nil
}

type PayViewPaymentInfoResponse struct {
	Items []*Currency `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *PayViewPaymentInfoResponse) Reset()                    { *m = PayViewPaymentInfoResponse{} }
func (m *PayViewPaymentInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*PayViewPaymentInfoResponse) ProtoMessage()               {}
func (*PayViewPaymentInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PayViewPaymentInfoResponse) GetItems() []*Currency {
	if m != nil {
		return m.Items
	}
	return nil
}

type PayViewCartResponse struct {
	Items []*Inventory `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *PayViewCartResponse) Reset()                    { *m = PayViewCartResponse{} }
func (m *PayViewCartResponse) String() string            { return proto.CompactTextString(m) }
func (*PayViewCartResponse) ProtoMessage()               {}
func (*PayViewCartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PayViewCartResponse) GetItems() []*Inventory {
	if m != nil {
		return m.Items
	}
	return nil
}

type PayPurchaseCartRequest struct {
	Body *PayPurchaseCartRequest_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *PayPurchaseCartRequest) Reset()                    { *m = PayPurchaseCartRequest{} }
func (m *PayPurchaseCartRequest) String() string            { return proto.CompactTextString(m) }
func (*PayPurchaseCartRequest) ProtoMessage()               {}
func (*PayPurchaseCartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PayPurchaseCartRequest) GetBody() *PayPurchaseCartRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type PayPurchaseCartRequest_Body struct {
	Currency *Currency `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
	Payment  int32     `protobuf:"varint,2,opt,name=payment" json:"payment,omitempty"`
}

func (m *PayPurchaseCartRequest_Body) Reset()                    { *m = PayPurchaseCartRequest_Body{} }
func (m *PayPurchaseCartRequest_Body) String() string            { return proto.CompactTextString(m) }
func (*PayPurchaseCartRequest_Body) ProtoMessage()               {}
func (*PayPurchaseCartRequest_Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *PayPurchaseCartRequest_Body) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *PayPurchaseCartRequest_Body) GetPayment() int32 {
	if m != nil {
		return m.Payment
	}
	return 0
}

type PayPurchaseCartResponse struct {
	CallUri string `protobuf:"bytes,1,opt,name=call_uri,json=callUri" json:"call_uri,omitempty"`
}

func (m *PayPurchaseCartResponse) Reset()                    { *m = PayPurchaseCartResponse{} }
func (m *PayPurchaseCartResponse) String() string            { return proto.CompactTextString(m) }
func (*PayPurchaseCartResponse) ProtoMessage()               {}
func (*PayPurchaseCartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PayPurchaseCartResponse) GetCallUri() string {
	if m != nil {
		return m.CallUri
	}
	return ""
}

type PayAddToCartRequest struct {
	// A specific item id you wish to purchase
	Id float64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
}

func (m *PayAddToCartRequest) Reset()                    { *m = PayAddToCartRequest{} }
func (m *PayAddToCartRequest) String() string            { return proto.CompactTextString(m) }
func (*PayAddToCartRequest) ProtoMessage()               {}
func (*PayAddToCartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PayAddToCartRequest) GetId() float64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PayUpdateOrderRequest struct {
	// Updated Vend Object
	Body *Vend `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	// ID of order that needs to be updated
	OrderId string `protobuf:"bytes,2,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *PayUpdateOrderRequest) Reset()                    { *m = PayUpdateOrderRequest{} }
func (m *PayUpdateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*PayUpdateOrderRequest) ProtoMessage()               {}
func (*PayUpdateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PayUpdateOrderRequest) GetBody() *Vend {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *PayUpdateOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayUpdateOrderResponse struct {
	CallBack string `protobuf:"bytes,1,opt,name=call_back,json=callBack" json:"call_back,omitempty"`
}

func (m *PayUpdateOrderResponse) Reset()                    { *m = PayUpdateOrderResponse{} }
func (m *PayUpdateOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*PayUpdateOrderResponse) ProtoMessage()               {}
func (*PayUpdateOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PayUpdateOrderResponse) GetCallBack() string {
	if m != nil {
		return m.CallBack
	}
	return ""
}

type PayReOrderItemsRequest struct {
	// ID of order to re-order
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *PayReOrderItemsRequest) Reset()                    { *m = PayReOrderItemsRequest{} }
func (m *PayReOrderItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*PayReOrderItemsRequest) ProtoMessage()               {}
func (*PayReOrderItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PayReOrderItemsRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type PayDeleteOrderRequest struct {
	// Order ID to delete
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *PayDeleteOrderRequest) Reset()                    { *m = PayDeleteOrderRequest{} }
func (m *PayDeleteOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*PayDeleteOrderRequest) ProtoMessage()               {}
func (*PayDeleteOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PayDeleteOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type SessionGetCurrentSessionResponse struct {
	// The session_id
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *SessionGetCurrentSessionResponse) Reset()         { *m = SessionGetCurrentSessionResponse{} }
func (m *SessionGetCurrentSessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionGetCurrentSessionResponse) ProtoMessage()    {}
func (*SessionGetCurrentSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

func (m *SessionGetCurrentSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type SessionLoginUserRequest struct {
	// The password for login in clear text
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	// The user name for login
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *SessionLoginUserRequest) Reset()                    { *m = SessionLoginUserRequest{} }
func (m *SessionLoginUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionLoginUserRequest) ProtoMessage()               {}
func (*SessionLoginUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SessionLoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SessionLoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type SessionCreateSessionResponse struct {
	// The user ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *SessionCreateSessionResponse) Reset()                    { *m = SessionCreateSessionResponse{} }
func (m *SessionCreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionCreateSessionResponse) ProtoMessage()               {}
func (*SessionCreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SessionCreateSessionResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SessionCreateUserRequest struct {
	// The created user object
	Body *User `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *SessionCreateUserRequest) Reset()                    { *m = SessionCreateUserRequest{} }
func (m *SessionCreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionCreateUserRequest) ProtoMessage()               {}
func (*SessionCreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SessionCreateUserRequest) GetBody() *User {
	if m != nil {
		return m.Body
	}
	return nil
}

type SessionCreateUserResponse struct {
	// The user ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *SessionCreateUserResponse) Reset()                    { *m = SessionCreateUserResponse{} }
func (m *SessionCreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionCreateUserResponse) ProtoMessage()               {}
func (*SessionCreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SessionCreateUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SessionGetUserByUserIdRequest struct {
	// the user or session ID
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *SessionGetUserByUserIdRequest) Reset()                    { *m = SessionGetUserByUserIdRequest{} }
func (m *SessionGetUserByUserIdRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionGetUserByUserIdRequest) ProtoMessage()               {}
func (*SessionGetUserByUserIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SessionGetUserByUserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SessionUpdateUserRequest struct {
	// Updated user object
	Body *User `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	// the user or session ID
	UserId string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *SessionUpdateUserRequest) Reset()                    { *m = SessionUpdateUserRequest{} }
func (m *SessionUpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionUpdateUserRequest) ProtoMessage()               {}
func (*SessionUpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SessionUpdateUserRequest) GetBody() *User {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *SessionUpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SessionDeleteUserRequest struct {
	// The name that needs to be deleted
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *SessionDeleteUserRequest) Reset()                    { *m = SessionDeleteUserRequest{} }
func (m *SessionDeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionDeleteUserRequest) ProtoMessage()               {}
func (*SessionDeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SessionDeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VendGetVendByIdRequest struct {
	// The id we want to query for transactions
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *VendGetVendByIdRequest) Reset()                    { *m = VendGetVendByIdRequest{} }
func (m *VendGetVendByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*VendGetVendByIdRequest) ProtoMessage()               {}
func (*VendGetVendByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *VendGetVendByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ApiResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *ApiResponse) Reset()                    { *m = ApiResponse{} }
func (m *ApiResponse) String() string            { return proto.CompactTextString(m) }
func (*ApiResponse) ProtoMessage()               {}
func (*ApiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ApiResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ApiResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Category struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Currency struct {
	Country string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	Format  string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Symbol  string `protobuf:"bytes,4,opt,name=symbol" json:"symbol,omitempty"`
}

func (m *Currency) Reset()                    { *m = Currency{} }
func (m *Currency) String() string            { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()               {}
func (*Currency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *Currency) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Currency) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type Inventory struct {
	Cost      int32    `protobuf:"varint,1,opt,name=cost" json:"cost,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name      string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PhotoUrls []string `protobuf:"bytes,4,rep,name=photoUrls" json:"photoUrls,omitempty"`
	Tags      []*Tag   `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Url       string   `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
}

func (m *Inventory) Reset()                    { *m = Inventory{} }
func (m *Inventory) String() string            { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()               {}
func (*Inventory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *Inventory) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Inventory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Inventory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Inventory) GetPhotoUrls() []string {
	if m != nil {
		return m.PhotoUrls
	}
	return nil
}

func (m *Inventory) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Inventory) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Tag struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Email     string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	Id        string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=lastName" json:"lastName,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Phone     string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	// User Status
	UserStatus int32  `protobuf:"varint,7,opt,name=userStatus" json:"userStatus,omitempty"`
	Username   string `protobuf:"bytes,8,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetUserStatus() int32 {
	if m != nil {
		return m.UserStatus
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Vend struct {
	Id     string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Items  []*Vend_Item    `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Status Vend_Vend_Statu `protobuf:"varint,3,opt,name=status,enum=shoppersshop_vendingmachine.Vend_Vend_Statu" json:"status,omitempty"`
	Total  int32           `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
}

func (m *Vend) Reset()                    { *m = Vend{} }
func (m *Vend) String() string            { return proto.CompactTextString(m) }
func (*Vend) ProtoMessage()               {}
func (*Vend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *Vend) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vend) GetItems() []*Vend_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Vend) GetStatus() Vend_Vend_Statu {
	if m != nil {
		return m.Status
	}
	return Vend_VEND_STATU_PLACED
}

func (m *Vend) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Vend_Item struct {
	Category *Category  `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	Item     *Inventory `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
	// The number of item x bought
	Quantity int32 `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *Vend_Item) Reset()                    { *m = Vend_Item{} }
func (m *Vend_Item) String() string            { return proto.CompactTextString(m) }
func (*Vend_Item) ProtoMessage()               {}
func (*Vend_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28, 0} }

func (m *Vend_Item) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Vend_Item) GetItem() *Inventory {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Vend_Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*InventorySearchAllItemCategoriesResponse)(nil), "shoppersshop_vendingmachine.InventorySearchAllItemCategoriesResponse")
	proto.RegisterType((*InventorySearchAllItemCategoriesResponse_Item)(nil), "shoppersshop_vendingmachine.InventorySearchAllItemCategoriesResponse.Item")
	proto.RegisterType((*InventorySearchForItemsRequest)(nil), "shoppersshop_vendingmachine.InventorySearchForItemsRequest")
	proto.RegisterType((*InventorySearchForItemsResponse)(nil), "shoppersshop_vendingmachine.InventorySearchForItemsResponse")
	proto.RegisterType((*PayViewPaymentInfoResponse)(nil), "shoppersshop_vendingmachine.PayViewPaymentInfoResponse")
	proto.RegisterType((*PayViewCartResponse)(nil), "shoppersshop_vendingmachine.PayViewCartResponse")
	proto.RegisterType((*PayPurchaseCartRequest)(nil), "shoppersshop_vendingmachine.PayPurchaseCartRequest")
	proto.RegisterType((*PayPurchaseCartRequest_Body)(nil), "shoppersshop_vendingmachine.PayPurchaseCartRequest.Body")
	proto.RegisterType((*PayPurchaseCartResponse)(nil), "shoppersshop_vendingmachine.PayPurchaseCartResponse")
	proto.RegisterType((*PayAddToCartRequest)(nil), "shoppersshop_vendingmachine.PayAddToCartRequest")
	proto.RegisterType((*PayUpdateOrderRequest)(nil), "shoppersshop_vendingmachine.PayUpdateOrderRequest")
	proto.RegisterType((*PayUpdateOrderResponse)(nil), "shoppersshop_vendingmachine.PayUpdateOrderResponse")
	proto.RegisterType((*PayReOrderItemsRequest)(nil), "shoppersshop_vendingmachine.PayReOrderItemsRequest")
	proto.RegisterType((*PayDeleteOrderRequest)(nil), "shoppersshop_vendingmachine.PayDeleteOrderRequest")
	proto.RegisterType((*SessionGetCurrentSessionResponse)(nil), "shoppersshop_vendingmachine.SessionGetCurrentSessionResponse")
	proto.RegisterType((*SessionLoginUserRequest)(nil), "shoppersshop_vendingmachine.SessionLoginUserRequest")
	proto.RegisterType((*SessionCreateSessionResponse)(nil), "shoppersshop_vendingmachine.SessionCreateSessionResponse")
	proto.RegisterType((*SessionCreateUserRequest)(nil), "shoppersshop_vendingmachine.SessionCreateUserRequest")
	proto.RegisterType((*SessionCreateUserResponse)(nil), "shoppersshop_vendingmachine.SessionCreateUserResponse")
	proto.RegisterType((*SessionGetUserByUserIdRequest)(nil), "shoppersshop_vendingmachine.SessionGetUserByUserIdRequest")
	proto.RegisterType((*SessionUpdateUserRequest)(nil), "shoppersshop_vendingmachine.SessionUpdateUserRequest")
	proto.RegisterType((*SessionDeleteUserRequest)(nil), "shoppersshop_vendingmachine.SessionDeleteUserRequest")
	proto.RegisterType((*VendGetVendByIdRequest)(nil), "shoppersshop_vendingmachine.VendGetVendByIdRequest")
	proto.RegisterType((*ApiResponse)(nil), "shoppersshop_vendingmachine.ApiResponse")
	proto.RegisterType((*Category)(nil), "shoppersshop_vendingmachine.Category")
	proto.RegisterType((*Currency)(nil), "shoppersshop_vendingmachine.Currency")
	proto.RegisterType((*Empty)(nil), "shoppersshop_vendingmachine.Empty")
	proto.RegisterType((*Inventory)(nil), "shoppersshop_vendingmachine.Inventory")
	proto.RegisterType((*Tag)(nil), "shoppersshop_vendingmachine.Tag")
	proto.RegisterType((*User)(nil), "shoppersshop_vendingmachine.User")
	proto.RegisterType((*Vend)(nil), "shoppersshop_vendingmachine.Vend")
	proto.RegisterType((*Vend_Item)(nil), "shoppersshop_vendingmachine.Vend.Item")
	proto.RegisterEnum("shoppersshop_vendingmachine.Vend_Vend_Statu", Vend_Vend_Statu_name, Vend_Vend_Statu_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SHOPPERSSHOP_VendingMachineService service

type SHOPPERSSHOP_VendingMachineServiceClient interface {
	// Finds Pets by status
	//
	// Get all stores once can vend the inventory by name
	InventorySearchAllItemCategories(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*InventorySearchAllItemCategoriesResponse, error)
	// Finds inventory items by query params
	//
	// Search the inventory by query params
	InventorySearchForItems(ctx context.Context, in *InventorySearchForItemsRequest, opts ...grpc.CallOption) (*InventorySearchForItemsResponse, error)
	// View all valid payment schemas
	PayViewPaymentInfo(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PayViewPaymentInfoResponse, error)
	// See all items in your virtual cart
	//
	// Shows all items in your cart
	PayViewCart(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PayViewCartResponse, error)
	// Initialize a vending transaction
	//
	// Purchases all items in your cart
	PayPurchaseCart(ctx context.Context, in *PayPurchaseCartRequest, opts ...grpc.CallOption) (*PayPurchaseCartResponse, error)
	// Add an item via id to your cart
	PayAddToCart(ctx context.Context, in *PayAddToCartRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Updates an old order
	//
	// Updates an old order IF it is not completed
	PayUpdateOrder(ctx context.Context, in *PayUpdateOrderRequest, opts ...grpc.CallOption) (*PayUpdateOrderResponse, error)
	// Re-order items
	//
	// Adds all items from the given order back to the cart
	PayReOrderItems(ctx context.Context, in *PayReOrderItemsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Deletes a order IF it is not complete
	//
	// Delete an outstanding order
	PayDeleteOrder(ctx context.Context, in *PayDeleteOrderRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Get the session
	//
	// Returns the current session ID or creates one
	SessionGetCurrentSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionGetCurrentSessionResponse, error)
	// Logs user into the system
	//
	// Logs in the current user into the vending machine
	SessionLoginUser(ctx context.Context, in *SessionLoginUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Logs out current logged in user session
	//
	// Logs out the given user
	SessionLogoutUser(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Creates a user session
	//
	// Creates a session with the given user
	SessionCreateSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionCreateSessionResponse, error)
	// Creates a new user
	//
	// Creates a user, returns the user id
	SessionCreateUser(ctx context.Context, in *SessionCreateUserRequest, opts ...grpc.CallOption) (*SessionCreateUserResponse, error)
	// Get session or user by ID
	//
	// Gets the session/user represented by the passed UUID
	SessionGetUserByUserId(ctx context.Context, in *SessionGetUserByUserIdRequest, opts ...grpc.CallOption) (*User, error)
	// Updated user
	//
	// This can only be done by the logged in user.
	SessionUpdateUser(ctx context.Context, in *SessionUpdateUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Delete user
	//
	// Deletes current user.
	SessionDeleteUser(ctx context.Context, in *SessionDeleteUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// web-hook endpoint representing vended items by this session
	//
	// The endpoint representing all of the items you've ever purchased - thanks!
	VendGetSessionVend(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Vend, error)
	// Web-hook and transaction query
	//
	// This endpoint gives access to transactions created by {TransactionId, UserId}
	VendGetVendById(ctx context.Context, in *VendGetVendByIdRequest, opts ...grpc.CallOption) (*Vend, error)
}

type sHOPPERSSHOP_VendingMachineServiceClient struct {
	cc *grpc.ClientConn
}

func NewSHOPPERSSHOP_VendingMachineServiceClient(cc *grpc.ClientConn) SHOPPERSSHOP_VendingMachineServiceClient {
	return &sHOPPERSSHOP_VendingMachineServiceClient{cc}
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) InventorySearchAllItemCategories(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*InventorySearchAllItemCategoriesResponse, error) {
	out := new(InventorySearchAllItemCategoriesResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/InventorySearchAllItemCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) InventorySearchForItems(ctx context.Context, in *InventorySearchForItemsRequest, opts ...grpc.CallOption) (*InventorySearchForItemsResponse, error) {
	out := new(InventorySearchForItemsResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/InventorySearchForItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayViewPaymentInfo(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PayViewPaymentInfoResponse, error) {
	out := new(PayViewPaymentInfoResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayViewPaymentInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayViewCart(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PayViewCartResponse, error) {
	out := new(PayViewCartResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayViewCart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayPurchaseCart(ctx context.Context, in *PayPurchaseCartRequest, opts ...grpc.CallOption) (*PayPurchaseCartResponse, error) {
	out := new(PayPurchaseCartResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayPurchaseCart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayAddToCart(ctx context.Context, in *PayAddToCartRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayAddToCart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayUpdateOrder(ctx context.Context, in *PayUpdateOrderRequest, opts ...grpc.CallOption) (*PayUpdateOrderResponse, error) {
	out := new(PayUpdateOrderResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayUpdateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayReOrderItems(ctx context.Context, in *PayReOrderItemsRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayReOrderItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) PayDeleteOrder(ctx context.Context, in *PayDeleteOrderRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayDeleteOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionGetCurrentSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionGetCurrentSessionResponse, error) {
	out := new(SessionGetCurrentSessionResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionGetCurrentSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionLoginUser(ctx context.Context, in *SessionLoginUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionLoginUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionLogoutUser(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionLogoutUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionCreateSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionCreateSessionResponse, error) {
	out := new(SessionCreateSessionResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionCreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionCreateUser(ctx context.Context, in *SessionCreateUserRequest, opts ...grpc.CallOption) (*SessionCreateUserResponse, error) {
	out := new(SessionCreateUserResponse)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionCreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionGetUserByUserId(ctx context.Context, in *SessionGetUserByUserIdRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionGetUserByUserId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionUpdateUser(ctx context.Context, in *SessionUpdateUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionUpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) SessionDeleteUser(ctx context.Context, in *SessionDeleteUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionDeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) VendGetSessionVend(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Vend, error) {
	out := new(Vend)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/VendGetSessionVend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHOPPERSSHOP_VendingMachineServiceClient) VendGetVendById(ctx context.Context, in *VendGetVendByIdRequest, opts ...grpc.CallOption) (*Vend, error) {
	out := new(Vend)
	err := grpc.Invoke(ctx, "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/VendGetVendById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SHOPPERSSHOP_VendingMachineService service

type SHOPPERSSHOP_VendingMachineServiceServer interface {
	// Finds Pets by status
	//
	// Get all stores once can vend the inventory by name
	InventorySearchAllItemCategories(context.Context, *google_protobuf.Empty) (*InventorySearchAllItemCategoriesResponse, error)
	// Finds inventory items by query params
	//
	// Search the inventory by query params
	InventorySearchForItems(context.Context, *InventorySearchForItemsRequest) (*InventorySearchForItemsResponse, error)
	// View all valid payment schemas
	PayViewPaymentInfo(context.Context, *google_protobuf.Empty) (*PayViewPaymentInfoResponse, error)
	// See all items in your virtual cart
	//
	// Shows all items in your cart
	PayViewCart(context.Context, *google_protobuf.Empty) (*PayViewCartResponse, error)
	// Initialize a vending transaction
	//
	// Purchases all items in your cart
	PayPurchaseCart(context.Context, *PayPurchaseCartRequest) (*PayPurchaseCartResponse, error)
	// Add an item via id to your cart
	PayAddToCart(context.Context, *PayAddToCartRequest) (*google_protobuf.Empty, error)
	// Updates an old order
	//
	// Updates an old order IF it is not completed
	PayUpdateOrder(context.Context, *PayUpdateOrderRequest) (*PayUpdateOrderResponse, error)
	// Re-order items
	//
	// Adds all items from the given order back to the cart
	PayReOrderItems(context.Context, *PayReOrderItemsRequest) (*google_protobuf.Empty, error)
	// Deletes a order IF it is not complete
	//
	// Delete an outstanding order
	PayDeleteOrder(context.Context, *PayDeleteOrderRequest) (*google_protobuf.Empty, error)
	// Get the session
	//
	// Returns the current session ID or creates one
	SessionGetCurrentSession(context.Context, *google_protobuf.Empty) (*SessionGetCurrentSessionResponse, error)
	// Logs user into the system
	//
	// Logs in the current user into the vending machine
	SessionLoginUser(context.Context, *SessionLoginUserRequest) (*google_protobuf.Empty, error)
	// Logs out current logged in user session
	//
	// Logs out the given user
	SessionLogoutUser(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	// Creates a user session
	//
	// Creates a session with the given user
	SessionCreateSession(context.Context, *google_protobuf.Empty) (*SessionCreateSessionResponse, error)
	// Creates a new user
	//
	// Creates a user, returns the user id
	SessionCreateUser(context.Context, *SessionCreateUserRequest) (*SessionCreateUserResponse, error)
	// Get session or user by ID
	//
	// Gets the session/user represented by the passed UUID
	SessionGetUserByUserId(context.Context, *SessionGetUserByUserIdRequest) (*User, error)
	// Updated user
	//
	// This can only be done by the logged in user.
	SessionUpdateUser(context.Context, *SessionUpdateUserRequest) (*google_protobuf.Empty, error)
	// Delete user
	//
	// Deletes current user.
	SessionDeleteUser(context.Context, *SessionDeleteUserRequest) (*google_protobuf.Empty, error)
	// web-hook endpoint representing vended items by this session
	//
	// The endpoint representing all of the items you've ever purchased - thanks!
	VendGetSessionVend(context.Context, *google_protobuf.Empty) (*Vend, error)
	// Web-hook and transaction query
	//
	// This endpoint gives access to transactions created by {TransactionId, UserId}
	VendGetVendById(context.Context, *VendGetVendByIdRequest) (*Vend, error)
}

func RegisterSHOPPERSSHOP_VendingMachineServiceServer(s *grpc.Server, srv SHOPPERSSHOP_VendingMachineServiceServer) {
	s.RegisterService(&_SHOPPERSSHOP_VendingMachineService_serviceDesc, srv)
}

func _SHOPPERSSHOP_VendingMachineService_InventorySearchAllItemCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).InventorySearchAllItemCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/InventorySearchAllItemCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).InventorySearchAllItemCategories(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_InventorySearchForItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventorySearchForItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).InventorySearchForItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/InventorySearchForItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).InventorySearchForItems(ctx, req.(*InventorySearchForItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayViewPaymentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayViewPaymentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayViewPaymentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayViewPaymentInfo(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayViewCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayViewCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayViewCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayViewCart(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayPurchaseCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayPurchaseCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayPurchaseCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayPurchaseCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayPurchaseCart(ctx, req.(*PayPurchaseCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayAddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayAddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayAddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayAddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayAddToCart(ctx, req.(*PayAddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayUpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayUpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayUpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayUpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayUpdateOrder(ctx, req.(*PayUpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayReOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReOrderItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayReOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayReOrderItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayReOrderItems(ctx, req.(*PayReOrderItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_PayDeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayDeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayDeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/PayDeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).PayDeleteOrder(ctx, req.(*PayDeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionGetCurrentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionGetCurrentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionGetCurrentSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionGetCurrentSession(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionLoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionLoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionLoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionLoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionLoginUser(ctx, req.(*SessionLoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionLogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionLogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionLogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionLogoutUser(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionCreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionCreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionCreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionCreateSession(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionCreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionCreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionCreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionCreateUser(ctx, req.(*SessionCreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionGetUserByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionGetUserByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionGetUserByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionGetUserByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionGetUserByUserId(ctx, req.(*SessionGetUserByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionUpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionUpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionUpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionUpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionUpdateUser(ctx, req.(*SessionUpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_SessionDeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionDeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/SessionDeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).SessionDeleteUser(ctx, req.(*SessionDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_VendGetSessionVend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).VendGetSessionVend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/VendGetSessionVend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).VendGetSessionVend(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHOPPERSSHOP_VendingMachineService_VendGetVendById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendGetVendByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).VendGetVendById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService/VendGetVendById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHOPPERSSHOP_VendingMachineServiceServer).VendGetVendById(ctx, req.(*VendGetVendByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SHOPPERSSHOP_VendingMachineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shoppersshop_vendingmachine.SHOPPERSSHOP_VendingMachineService",
	HandlerType: (*SHOPPERSSHOP_VendingMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InventorySearchAllItemCategories",
			Handler:    _SHOPPERSSHOP_VendingMachineService_InventorySearchAllItemCategories_Handler,
		},
		{
			MethodName: "InventorySearchForItems",
			Handler:    _SHOPPERSSHOP_VendingMachineService_InventorySearchForItems_Handler,
		},
		{
			MethodName: "PayViewPaymentInfo",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayViewPaymentInfo_Handler,
		},
		{
			MethodName: "PayViewCart",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayViewCart_Handler,
		},
		{
			MethodName: "PayPurchaseCart",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayPurchaseCart_Handler,
		},
		{
			MethodName: "PayAddToCart",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayAddToCart_Handler,
		},
		{
			MethodName: "PayUpdateOrder",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayUpdateOrder_Handler,
		},
		{
			MethodName: "PayReOrderItems",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayReOrderItems_Handler,
		},
		{
			MethodName: "PayDeleteOrder",
			Handler:    _SHOPPERSSHOP_VendingMachineService_PayDeleteOrder_Handler,
		},
		{
			MethodName: "SessionGetCurrentSession",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionGetCurrentSession_Handler,
		},
		{
			MethodName: "SessionLoginUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionLoginUser_Handler,
		},
		{
			MethodName: "SessionLogoutUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionLogoutUser_Handler,
		},
		{
			MethodName: "SessionCreateSession",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionCreateSession_Handler,
		},
		{
			MethodName: "SessionCreateUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionCreateUser_Handler,
		},
		{
			MethodName: "SessionGetUserByUserId",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionGetUserByUserId_Handler,
		},
		{
			MethodName: "SessionUpdateUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionUpdateUser_Handler,
		},
		{
			MethodName: "SessionDeleteUser",
			Handler:    _SHOPPERSSHOP_VendingMachineService_SessionDeleteUser_Handler,
		},
		{
			MethodName: "VendGetSessionVend",
			Handler:    _SHOPPERSSHOP_VendingMachineService_VendGetSessionVend_Handler,
		},
		{
			MethodName: "VendGetVendById",
			Handler:    _SHOPPERSSHOP_VendingMachineService_VendGetVendById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vending/vending.proto",
}

func init() { proto.RegisterFile("vending/vending.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x6e, 0x1b, 0x55,
	0x14, 0x66, 0xfc, 0x93, 0xc4, 0x27, 0xa8, 0x4d, 0x6e, 0x9b, 0xc4, 0x99, 0x24, 0xad, 0x3b, 0x6a,
	0x4b, 0xa8, 0x90, 0x4d, 0xd3, 0x94, 0x42, 0x5b, 0x16, 0x4e, 0x6c, 0x4a, 0x50, 0x68, 0xcc, 0x38,
	0x89, 0xc4, 0xca, 0x4c, 0xec, 0x1b, 0x7b, 0x54, 0x7b, 0xee, 0x74, 0xe6, 0xba, 0xd5, 0xa8, 0x2a,
	0x15, 0xb0, 0x41, 0x42, 0x62, 0xc3, 0x1a, 0x09, 0x10, 0x1b, 0x78, 0x04, 0x16, 0x2c, 0xd9, 0xb0,
	0x84, 0x47, 0xe0, 0x05, 0x78, 0x03, 0x74, 0x7f, 0xe6, 0xc7, 0x63, 0x8f, 0xed, 0x94, 0x6e, 0xe2,
	0x39, 0x77, 0xee, 0x39, 0xe7, 0x3b, 0xdf, 0xdc, 0x9f, 0xef, 0x04, 0x96, 0x9e, 0x60, 0xab, 0x65,
	0x5a, 0xed, 0x92, 0xfc, 0x2d, 0xda, 0x0e, 0xa1, 0x04, 0xad, 0xb9, 0x1d, 0x62, 0xdb, 0xd8, 0x71,
	0xd9, 0x6f, 0x43, 0xbe, 0xeb, 0x19, 0xcd, 0x8e, 0x69, 0x61, 0x75, 0xad, 0x4d, 0x48, 0xbb, 0x8b,
	0x4b, 0x7c, 0xea, 0x49, 0xff, 0xb4, 0x84, 0x7b, 0x36, 0xf5, 0x84, 0xa7, 0xba, 0x2e, 0x5f, 0x1a,
	0xb6, 0x59, 0x32, 0x2c, 0x8b, 0x50, 0x83, 0x9a, 0xc4, 0x72, 0xc5, 0x5b, 0xed, 0x5f, 0x05, 0x36,
	0xf7, 0xac, 0x27, 0xd8, 0xa2, 0xc4, 0xf1, 0xea, 0xd8, 0x70, 0x9a, 0x9d, 0x72, 0xb7, 0xbb, 0x47,
	0x71, 0x6f, 0xd7, 0xa0, 0xb8, 0x4d, 0x1c, 0x13, 0xbb, 0x3a, 0x76, 0x6d, 0x62, 0xb9, 0x18, 0x7d,
	0x06, 0x59, 0x93, 0xe2, 0x9e, 0x9b, 0x57, 0x0a, 0xe9, 0xcd, 0xf9, 0xad, 0x8f, 0x8a, 0x63, 0x40,
	0x15, 0xa7, 0x8d, 0x5a, 0x64, 0xc3, 0xba, 0x08, 0xac, 0x36, 0x21, 0xc3, 0x4c, 0x54, 0x05, 0x68,
	0x06, 0x33, 0xf3, 0x4a, 0x41, 0xd9, 0x9c, 0xdf, 0xba, 0x36, 0x36, 0x9d, 0x0c, 0xec, 0xe9, 0x11,
	0x47, 0x74, 0x11, 0xb2, 0x2e, 0x25, 0x0e, 0xce, 0xa7, 0x0a, 0xca, 0x66, 0x4e, 0x17, 0x86, 0x76,
	0x0a, 0x97, 0x62, 0xe0, 0x3e, 0x20, 0x0e, 0x4b, 0xeb, 0xea, 0xf8, 0x71, 0x1f, 0xbb, 0x14, 0xa9,
	0x30, 0x27, 0xa3, 0x78, 0xbc, 0xd6, 0x9c, 0x1e, 0xd8, 0x08, 0x41, 0xc6, 0x32, 0x7a, 0x2c, 0x24,
	0x1b, 0xe7, 0xcf, 0x2c, 0x8f, 0xed, 0x98, 0x4d, 0x9c, 0x4f, 0x17, 0x94, 0xcd, 0xac, 0x2e, 0x0c,
	0xad, 0x01, 0x97, 0x13, 0xf3, 0x48, 0x46, 0xef, 0x0f, 0x32, 0x7a, 0x7d, 0x3a, 0x46, 0x25, 0x5b,
	0xda, 0xa7, 0xa0, 0xd6, 0x0c, 0xef, 0xd8, 0xc4, 0x4f, 0x6b, 0x86, 0xd7, 0xc3, 0x16, 0xdd, 0xb3,
	0x4e, 0x49, 0x10, 0xfb, 0xde, 0x60, 0xec, 0x09, 0xf4, 0xf5, 0x1d, 0x07, 0x5b, 0xcd, 0x20, 0x74,
	0x1d, 0x2e, 0xc8, 0xd0, 0xbb, 0x86, 0x43, 0x5f, 0x11, 0xde, 0x3f, 0x15, 0x58, 0xae, 0x19, 0x5e,
	0xad, 0xef, 0x34, 0x3b, 0x86, 0x8b, 0x45, 0x64, 0xc1, 0xf8, 0x3e, 0x64, 0x4e, 0x48, 0xcb, 0x93,
	0x9f, 0xfa, 0xdd, 0xb1, 0x71, 0x47, 0x87, 0x28, 0xee, 0x90, 0x96, 0xa7, 0xf3, 0x28, 0x6c, 0x19,
	0x31, 0x0b, 0x95, 0x61, 0xae, 0x29, 0x0b, 0x9b, 0x6e, 0x11, 0xf9, 0x2c, 0x04, 0x6e, 0x28, 0x0f,
	0xb3, 0xb6, 0x20, 0x97, 0x2f, 0xa2, 0xac, 0xee, 0x9b, 0xda, 0x36, 0xac, 0x0c, 0x21, 0x91, 0x34,
	0xad, 0xb2, 0xf5, 0xd3, 0xed, 0x36, 0xfa, 0x8e, 0xc9, 0xf3, 0xe6, 0xf4, 0x59, 0x66, 0x1f, 0x39,
	0xa6, 0x76, 0x8d, 0x13, 0x5b, 0x6e, 0xb5, 0x0e, 0x49, 0xb4, 0xfe, 0x73, 0x90, 0x32, 0x5b, 0x7c,
	0xae, 0xa2, 0xa7, 0xcc, 0x96, 0xd6, 0x81, 0xa5, 0x9a, 0xe1, 0x1d, 0xd9, 0x2d, 0x83, 0xe2, 0x03,
	0xa7, 0x85, 0x1d, 0x7f, 0xe2, 0xed, 0x01, 0xa2, 0xae, 0x8c, 0x2d, 0xe7, 0x18, 0x5b, 0x2d, 0xc1,
	0x08, 0x2b, 0x83, 0xb0, 0x30, 0x7b, 0x2d, 0xb9, 0x17, 0x7c, 0x53, 0xbb, 0xcd, 0xbf, 0xc9, 0x40,
	0x26, 0x59, 0xc5, 0x1a, 0xe4, 0x78, 0x15, 0x27, 0x46, 0xf3, 0x91, 0x2c, 0x83, 0x97, 0xb5, 0x63,
	0x34, 0x1f, 0x69, 0x5b, 0xdc, 0x4d, 0x17, 0x2e, 0x03, 0x9b, 0x27, 0x92, 0x4a, 0x19, 0x4c, 0x75,
	0x93, 0x17, 0x55, 0xc1, 0x5d, 0x1c, 0x2b, 0x2a, 0xd9, 0xa5, 0x0c, 0x85, 0x3a, 0x76, 0x5d, 0x93,
	0x58, 0x0f, 0x30, 0x15, 0x9f, 0x87, 0xca, 0x81, 0x00, 0xe7, 0x06, 0x80, 0x2b, 0x86, 0x1a, 0xa6,
	0x1f, 0x20, 0x27, 0x47, 0xf6, 0x5a, 0xda, 0x27, 0xb0, 0x22, 0x3d, 0xf6, 0x49, 0xdb, 0xb4, 0x8e,
	0xdc, 0x30, 0xaf, 0x0a, 0x73, 0xb6, 0xe1, 0xba, 0x4f, 0x89, 0xe3, 0xfb, 0x05, 0x36, 0x7b, 0xd7,
	0x77, 0xb1, 0x23, 0xf7, 0x3a, 0x7f, 0xe7, 0xdb, 0xda, 0x1d, 0x58, 0x97, 0x21, 0x77, 0x1d, 0x6c,
	0x50, 0x1c, 0x47, 0xb4, 0x02, 0xb3, 0x6c, 0x6e, 0x08, 0x67, 0x86, 0x99, 0x1c, 0x4b, 0x7e, 0xc0,
	0x31, 0x0a, 0xe6, 0x2c, 0x5f, 0x96, 0xfb, 0xf1, 0xe9, 0xda, 0x36, 0xac, 0x8e, 0x08, 0x39, 0x09,
	0xc8, 0x1d, 0xd8, 0x08, 0x79, 0x65, 0x2e, 0x3b, 0xde, 0x11, 0x7f, 0xe3, 0xa3, 0x59, 0x06, 0x39,
	0x35, 0xe6, 0x68, 0x06, 0x15, 0x88, 0x25, 0xf3, 0xff, 0x2b, 0x88, 0xa4, 0x4a, 0x0d, 0xa4, 0xda,
	0x0a, 0x52, 0x89, 0x25, 0x13, 0x4d, 0x95, 0x04, 0x6f, 0x13, 0x96, 0xd9, 0xaa, 0x7f, 0x80, 0x29,
	0xfb, 0xd9, 0xf1, 0xc2, 0x82, 0xc2, 0x1d, 0x96, 0xe3, 0x3b, 0xec, 0x00, 0xe6, 0xcb, 0xb6, 0x19,
	0x30, 0x85, 0x20, 0xd3, 0x24, 0x2d, 0xcc, 0x27, 0x64, 0x75, 0xfe, 0xcc, 0x96, 0x65, 0x0f, 0xbb,
	0xae, 0xd1, 0xf6, 0x57, 0x80, 0x6f, 0xb2, 0xd9, 0xd4, 0xb3, 0xc5, 0x79, 0x9f, 0xd3, 0xf9, 0xb3,
	0x56, 0x84, 0x39, 0xff, 0x12, 0x8a, 0x27, 0x8b, 0x5c, 0x1a, 0x8a, 0x7f, 0x69, 0x68, 0x1d, 0x98,
	0xdb, 0x8d, 0x9c, 0x32, 0x4d, 0xd2, 0xb7, 0xa8, 0xe3, 0x05, 0xe7, 0x85, 0x30, 0x59, 0xa1, 0xa7,
	0xc4, 0xe9, 0x19, 0xd4, 0x27, 0x47, 0x58, 0x41, 0xc4, 0x74, 0x18, 0x91, 0xcd, 0x75, 0xbd, 0xde,
	0x09, 0xe9, 0xe6, 0x33, 0x62, 0xae, 0xb0, 0xb4, 0x59, 0xc8, 0x56, 0x99, 0x22, 0xd0, 0x7e, 0x51,
	0x20, 0x17, 0x9c, 0xca, 0xa2, 0x64, 0x97, 0x86, 0x25, 0x07, 0x2c, 0xa5, 0x86, 0x80, 0x47, 0xd3,
	0xac, 0x43, 0xce, 0xee, 0x10, 0x4a, 0x8e, 0x9c, 0xae, 0x9b, 0xcf, 0xf0, 0x6b, 0x30, 0x1c, 0x40,
	0xdb, 0x90, 0xa1, 0x46, 0xdb, 0xcd, 0x67, 0xf9, 0x0d, 0x51, 0x18, 0xbb, 0x08, 0x0e, 0x8d, 0xb6,
	0xce, 0x67, 0xa3, 0x05, 0x48, 0xf7, 0x9d, 0x6e, 0x7e, 0x86, 0xa7, 0x61, 0x8f, 0xda, 0x9b, 0x90,
	0x3e, 0x34, 0xda, 0x53, 0x31, 0xf9, 0xb7, 0x02, 0x19, 0xb6, 0x38, 0xd8, 0x3d, 0x8c, 0x7b, 0x86,
	0xd9, 0x95, 0xf3, 0x85, 0xc1, 0xf0, 0x9e, 0x9a, 0x8e, 0x4b, 0x1f, 0x86, 0x7e, 0xe1, 0x80, 0x4c,
	0x90, 0x0e, 0x12, 0xa8, 0x30, 0xd7, 0x35, 0xe4, 0x64, 0x41, 0x63, 0x60, 0x0f, 0x9c, 0x17, 0xd9,
	0xd8, 0x79, 0xc1, 0x34, 0x40, 0x87, 0x58, 0x58, 0xd6, 0x20, 0x0c, 0x74, 0x09, 0x80, 0xad, 0xcc,
	0x3a, 0x35, 0x68, 0xdf, 0xcd, 0xcf, 0x72, 0xa6, 0x23, 0x23, 0x03, 0xa7, 0xcc, 0x5c, 0xec, 0x94,
	0xf9, 0x23, 0x0d, 0x19, 0xb6, 0x8a, 0x87, 0x38, 0x08, 0x6e, 0xe1, 0xd4, 0x14, 0xb7, 0x30, 0x8b,
	0x10, 0xd5, 0x58, 0xa8, 0x02, 0x33, 0xae, 0x80, 0xc3, 0x8a, 0x3e, 0xb7, 0xf5, 0xd6, 0x64, 0x77,
	0xf6, 0xa7, 0xc1, 0x11, 0xeb, 0xd2, 0x97, 0x95, 0x4b, 0x09, 0x35, 0xc4, 0x52, 0xcb, 0xea, 0xc2,
	0x50, 0x7f, 0x54, 0xa4, 0x80, 0x2b, 0x0f, 0x28, 0xa8, 0x33, 0xc8, 0xb7, 0x50, 0x68, 0xdd, 0x85,
	0x0c, 0x03, 0xcc, 0xbf, 0xd8, 0xf4, 0x52, 0x83, 0xfb, 0x30, 0x5a, 0x1f, 0xf7, 0x0d, 0x8b, 0x9a,
	0xd4, 0x93, 0x9a, 0x2c, 0xb0, 0x35, 0x1b, 0x20, 0xac, 0x07, 0x2d, 0xc1, 0xe2, 0x71, 0xf5, 0x61,
	0xa5, 0x51, 0x3f, 0x2c, 0x1f, 0x1e, 0x35, 0x6a, 0xfb, 0xe5, 0xdd, 0x6a, 0x65, 0xe1, 0x35, 0xb4,
	0x02, 0x17, 0x22, 0xc3, 0xe5, 0x5a, 0x4d, 0x3f, 0x38, 0xae, 0x56, 0x16, 0x14, 0x94, 0x87, 0x8b,
	0x91, 0x17, 0x95, 0xea, 0xfe, 0xde, 0x71, 0x55, 0xaf, 0x56, 0x16, 0x52, 0xb1, 0x37, 0xbb, 0xe5,
	0x87, 0xbb, 0xd5, 0xfd, 0xfd, 0x6a, 0x65, 0x21, 0xbd, 0xf5, 0xfb, 0x12, 0x68, 0xf5, 0x0f, 0x0f,
	0x6a, 0xb5, 0xaa, 0x5e, 0x67, 0xbf, 0x8d, 0x63, 0x81, 0xfe, 0x63, 0x81, 0xbe, 0x8e, 0x9d, 0x27,
	0x66, 0x13, 0xa3, 0x1f, 0x14, 0x28, 0x4c, 0x52, 0xcd, 0x68, 0xb9, 0x28, 0xf4, 0x7c, 0xd1, 0x17,
	0xfb, 0x45, 0xbe, 0xb5, 0xd5, 0xea, 0x2b, 0x11, 0xe3, 0xda, 0xc6, 0x97, 0x7f, 0xfd, 0xf3, 0x5d,
	0x6a, 0x05, 0x2d, 0x95, 0x82, 0x3e, 0xe4, 0x66, 0xc9, 0x0c, 0x8e, 0x8c, 0xdf, 0x14, 0x58, 0x49,
	0xd0, 0xb4, 0xe8, 0xde, 0x59, 0x10, 0xc4, 0x14, 0xb7, 0x7a, 0xff, 0xe5, 0x9c, 0x25, 0xea, 0xab,
	0x1c, 0xf5, 0x25, 0xb4, 0x3e, 0x12, 0x75, 0xc9, 0xe5, 0x5e, 0xe8, 0x73, 0x40, 0xc3, 0x72, 0x39,
	0x91, 0xd0, 0x3b, 0x93, 0x34, 0x68, 0x82, 0xee, 0xd6, 0x56, 0x38, 0x98, 0x45, 0x74, 0x3e, 0x0a,
	0xc6, 0x36, 0x3c, 0xe4, 0xc1, 0x7c, 0x44, 0x53, 0x27, 0x26, 0x7e, 0x7b, 0x9a, 0xc4, 0x51, 0xb9,
	0xa9, 0x15, 0x78, 0x46, 0x15, 0xe5, 0x63, 0x19, 0x4b, 0xb6, 0x14, 0xa7, 0xe8, 0x67, 0x05, 0xce,
	0xc7, 0xc4, 0x2a, 0xba, 0xf5, 0x12, 0x22, 0x5b, 0xdd, 0x3e, 0x9b, 0x93, 0x04, 0x78, 0x9d, 0x03,
	0x2c, 0x68, 0x89, 0x00, 0xef, 0x0a, 0x25, 0xf0, 0x02, 0x5e, 0x8f, 0x8a, 0x63, 0x34, 0x91, 0x8a,
	0xb8, 0x8e, 0x56, 0x13, 0x48, 0xd5, 0xae, 0x71, 0x04, 0x97, 0xd5, 0x8d, 0x24, 0x04, 0xa5, 0x67,
	0x66, 0xeb, 0x39, 0xfa, 0x49, 0x81, 0x73, 0x83, 0x6a, 0x18, 0x6d, 0x4d, 0xc2, 0x30, 0x2c, 0xd2,
	0xd5, 0x5b, 0x67, 0xf2, 0x91, 0x24, 0xbd, 0xc1, 0x21, 0x5e, 0x51, 0x57, 0xe3, 0x10, 0x9f, 0x49,
	0x31, 0xfc, 0x5c, 0xb2, 0xf4, 0x85, 0xf8, 0x98, 0x51, 0xed, 0x3d, 0xf9, 0x63, 0x8e, 0x50, 0xea,
	0x89, 0x64, 0x5d, 0xe1, 0x48, 0xd6, 0xb4, 0x64, 0x24, 0xe8, 0x05, 0xe7, 0x29, 0x22, 0xe5, 0x27,
	0xf3, 0x34, 0xac, 0xfb, 0x27, 0x01, 0xb8, 0x31, 0x06, 0xc0, 0xb7, 0x4a, 0xa0, 0x0e, 0x87, 0x3a,
	0x83, 0xc4, 0xad, 0xf5, 0xfe, 0x58, 0x8c, 0x93, 0x1a, 0x0d, 0x6d, 0x8d, 0xc3, 0x5a, 0x42, 0x17,
	0xa2, 0xb0, 0x64, 0xa3, 0x81, 0xbe, 0x52, 0x60, 0x21, 0xde, 0x67, 0xa0, 0xed, 0x69, 0x12, 0xc6,
	0xdb, 0x92, 0x49, 0xb4, 0xa0, 0xd5, 0x11, 0xf9, 0x4b, 0x5d, 0x16, 0x05, 0xb5, 0x61, 0x31, 0x8c,
	0x4a, 0xfa, 0x5c, 0xda, 0x27, 0xd2, 0x91, 0x94, 0x47, 0xe3, 0x79, 0xd6, 0x35, 0x35, 0x21, 0x0f,
	0xe9, 0x53, 0xf4, 0x8d, 0x02, 0x17, 0x47, 0xf5, 0x40, 0x89, 0xc9, 0xde, 0x9b, 0x86, 0x8a, 0x91,
	0xed, 0x94, 0x7f, 0xbe, 0xa9, 0xf9, 0x51, 0x78, 0x98, 0x5c, 0x42, 0xbf, 0x2a, 0x41, 0xdd, 0x61,
	0x17, 0x84, 0x6e, 0x4f, 0x9f, 0x32, 0x4a, 0xff, 0x3b, 0x67, 0x75, 0x1b, 0x77, 0xca, 0x45, 0x61,
	0xca, 0xfd, 0xfb, 0xbd, 0x02, 0xcb, 0xa3, 0x9b, 0x2f, 0x74, 0x77, 0xca, 0x05, 0x3a, 0xa2, 0x63,
	0x53, 0x27, 0xf7, 0x5b, 0xa3, 0xef, 0x49, 0x1f, 0xe1, 0x33, 0xd1, 0x42, 0xf1, 0xad, 0xb5, 0x38,
	0xd4, 0xe3, 0x4d, 0x47, 0xe6, 0x50, 0x4f, 0x98, 0xb8, 0xc6, 0x6e, 0x70, 0x28, 0x57, 0xd5, 0xb1,
	0x50, 0x24, 0x61, 0x5f, 0x87, 0x80, 0xc2, 0x4e, 0x70, 0x3a, 0x40, 0x43, 0x9d, 0x63, 0x22, 0x20,
	0xc9, 0xcd, 0x8d, 0xf1, 0xdc, 0x98, 0x80, 0x64, 0x7f, 0x29, 0x13, 0x70, 0x81, 0x9e, 0xb4, 0xe6,
	0x27, 0xff, 0x7b, 0x46, 0xcb, 0xf3, 0xb4, 0x08, 0x2d, 0x44, 0xd3, 0xb2, 0x47, 0x56, 0xf5, 0xf9,
	0x58, 0x2f, 0x3b, 0xe1, 0x98, 0x1f, 0xdd, 0xf9, 0x4e, 0x83, 0x62, 0xa4, 0xec, 0x63, 0x8f, 0xfc,
	0x5a, 0x3c, 0x99, 0xe1, 0x75, 0xdd, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x60, 0xe8, 0x1b,
	0x9d, 0x16, 0x00, 0x00,
}
